### PR TITLE
Adding CddInterface & NConvex

### PR DESCRIPTION
**Pull request by kamalsaleh**
After many very Valuable PR's and comments from @fingolfin , I believe the both packages `CddInterface` and `NConvex` are ready for a second review. Any further comments or suggestions are very welcome.

This PR is based on the discussion https://github.com/homalg-project/homalg_project/issues/212

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Thanks. CddInterface tests pass, while NConvex is not loadable (this test drops a clone of the repository being tested into the Docker container with the selection of packages picked up for the redistribution with GAP, so clearly there is no CddInterface there yet).

Regarding NConvex, we can wait till CddInterface will be picked up. If you will update both quote often in the future, you may want to create the prerequisites.sh (as documented in the README at https://github.com/gap-infra/gap-docker-pkg-tests-master-devel) to download or clone a fresh version of CddInterface. If not, we can simply wait.

About cddlib, I think it's fine to install it from a script now, but in the future we can simply install it into the Docker container that we use for tests (namely into https://github.com/gap-system/gap-docker-base) and remove the need in the special case to use your `./install.sh ${GAP_HOME}` at all. I presume that if there is a system Cddlib, then just the standard `bin/InstPackages.sh` will build the package?

**Comment by kamalsaleh** [comment]
You are right!, if the package libcdd-dev is already installed in the system, then `bin/InstPackages.sh` should be able to install the package, I have updated the README.md file to mention this https://github.com/homalg-project/CddInterface/commit/5e0b815856e22c29ae764340d101120596438187 .

**Comment by kamalsaleh** [comment]
If you wish, I can create a PR to [gap-docker-base](https://github.com/gap-system/gap-docker-base) to pre-install `cddlib-dev`?, then as you said, there will be no need for the special case `./install.sh ${GAP_HOME}`

**Comment by kamalsaleh** [comment]
Also, I have already added a `prerequisites.sh` to the CddInterface package, hence I think `ci.sh` should work even without my edit.

**Comment by alex-konovalov** [comment]
@kamalsaleh thanks - if you have `prerequisites.sh`, then maybe you can update this PR to use it instead of `install.sh` - that will be also only temporarily, since indeed the way to go it to update [gap-docker-base](https://github.com/gap-system/gap-docker-base) to add `cddlib-dev` - a PR there will be appreciated.

**Pull request merged**
